
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkgmyxedqsbmcmacgqbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZ215eGVkcXNibWNtYWNncWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODc5NjQsImV4cCI6MjA1ODk2Mzk2NH0.PN1X5yJS6KhLlHq3EfC6VNoMzHeZc7uBgQ3xvj42VyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
